# Generated by Django 3.0.6 on 2020-06-10 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
    ]
